version: '3.4'
services:
  api:
    build:
      context: .
    environment:
      - DATABASE_HOST
      - DATABASE_PORT
      - DATABASE_NAME
      - DATABASE_USERNAME
      - DATABASE_PASSWORD
      - DATABASE_SSL
      - HOST
      - PORT
      - URL
      - ADMIN_JWT_SECRET
      - PUBLIC_URL
      - STRAPI_URL
    ports:
      - "8010:80"