version: '3.4'
services:
  api_f6sny_com:
    build:
      context: .
    environment:
      - DATABASE_HOST
      - DATABASE_PORT
      - DATABASE_NAME
      - DATABASE_USERNAME
      - DATABASE_PASSWORD
      - DATABASE_SSL
      - HOST
      - PORT
      - URL
      - ADMIN_JWT_SECRET
    ports:
      - "8010:80"