replicaCount: 3

image:
  repository: ghcr.io/f6sny/api.f6sny.com
  tag: latest

service:
  type: ClusterIP
  port: 1337
  containerPort: 1337
  nodePort: 31337

externalSecrets:
  enabled: true

ingress:
  enabled: true
  className: nginx
  annotations:
    cert-manager.io/cluster-issuer: http01-clusterissuer  # new annotation
    nginx.ingress.kubernetes.io/ssl-redirect: "true"         # new annotation
    nginx.ingress.kubernetes.io/force-ssl-redirect: "true"     # new annotation
  hosts:
    - host: api-next.f6sny.com                            # override host
      paths:
        - path: /                                          # override path
          pathType: ImplementationSpecific                # override pathType
  tls:
    - hosts:
        - api-next.f6sny.com                             # TLS host
      secretName: f6sny-api-v5-tls                           # TLS secret

resources:
  requests:
    memory: "256Mi"
    cpu: "100m"
  limits:
    memory: "512Mi"
    cpu: "500m"


affinity:
  podAntiAffinity:
    preferredDuringSchedulingIgnoredDuringExecution:
      - weight: 1
        podAffinityTerm:
          labelSelector:
            matchExpressions:
              - key: app.kubernetes.io/instance
                operator: In
                values:
                  - strapi
          topologyKey: kubernetes.io/hostname
