apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: f6sny-api-v5-hpa
  namespace: f6sny
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: f6sny-api-v5
  minReplicas: 1
  maxReplicas: 5
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 70
