apiVersion: v1
kind: Service
metadata:
  name: f6sny-api-v5
spec:
  selector:
    app: f6sny-api-v5
    component: backend
  ports:
    - port: 1337
      targetPort: 1337
      protocol: TCP
  type: ClusterIP 