{{- if .Values.externalSecrets.enabled }}
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: {{ include "strapi-chart.fullname" . }}
spec:
  refreshInterval: "15m"
  secretStoreRef:
    name: vault-backend
    kind: ClusterSecretStore
  target:
    name: {{ include "strapi-chart.fullname" . }}
    creationPolicy: Owner
  data:
  {{- toYaml .Values.externalSecrets.data | nindent 2 }}
{{- end }}
